version: "3.7"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "8432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test-db